{
 "title": "OpenStack Hypervisor Status",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "influxdb" },
   {
    "name": "instance",
    "query": "show tag values from \"ServiceStatus\" with key=instance"
   },
   {
    "name": "host",
    "query": "show tag values from \"ServiceStatus\" with key=host"
   },
   {
    "name": "service",
    "query": "show tag values from \"ServiceStatus\" with key=service"
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Hypervisor Status",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "# OpenStack Hypervisor Status: Prod"
   }
  },
  {
   "title": "Hypervisors full",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ServiceStatus",
     "query": "SELECT sum(\"full\") FROM \"ServiceStatus\" WHERE (\"instance\"::tag =~ /^$instance$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "full" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "instance::tag", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Hypervisors CPU full",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ServiceStatus",
     "select": [
      [
       { "params": [ "cpufull" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "instance::tag", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Hypervisors Memory full",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ServiceStatus",
     "query": "SELECT sum(\"memfull\") FROM \"ServiceStatus\" WHERE (\"aggregate\"::tag =~ /^$instance$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "memfull" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "instance::tag", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "% HVs Active and Full",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($B / $A) *100", "type": "math" }
   ]
  },
  {
   "title": "% HVs Active and CPU Full",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($B / $A) *100", "type": "math" }
   ]
  },
  {
   "title": "% HVs Active and Memory Full",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($B / $A) *100", "type": "math" }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Hypervisor CPU Available",
   "type": "table",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "host::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ServiceStatus",
     "query": "SELECT last(\"cpuavailable\") FROM \"autogen\".\"ServiceStatus\" WHERE (\"instance\"::tag =~ /^$instance$/ AND \"service\"::tag = '\"hv\"' AND \"host\"::tag =~ /^$host$/) GROUP BY \"host\"::tag fill(null)",
     "select": [
      [
       { "params": [ "cpuavailable" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "instance::tag", "operator": "=~", "value": "/^$instance$/" },
      {
       "condition": "AND",
       "key": "service::tag",
       "operator": "=",
       "value": "\"hv\""
      },
      { "condition": "AND", "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  }
 ]
}