{
 "title": "Cloud Service Availability",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Instance", "query": "Prod, PreProd" }
  ]
 },
 "panels": [
  {
   "title": "Service Availability",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# ${Instance} Cloud Service - Current Availability\n"
   }
  },
  { "title": "VM Creation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "VM Creation (Internal)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(\"success\") FROM \"VMTasks-boot_runcommand_delete\" WHERE (\"instance\" =~  /$Instance$/ AND \"network\" != 'MonitoringPrivate') AND $timeFilter GROUP BY time($interval) fill(null)"
    }
   ]
  },
  {
   "title": "VM Creation (Private)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "SELECT mean(\"success\") FROM \"VMTasks-boot_runcommand_delete\" WHERE (\"instance\" =~  /$Instance$/ AND \"network\" = 'MonitoringPrivate') AND  $timeFilter GROUP BY time($interval)"
    }
   ]
  },
  { "title": "OpenStack Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Keystone",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "SELECT last(\"success\") FROM \"KeystoneBasic-create_tenant_with_users\" WHERE (\"instance\" =~  /$Instance$/) AND  $timeFilter GROUP BY time($interval)"
    }
   ]
  },
  {
   "title": "Neutron",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "SELECT last(\"success\") FROM \"NeutronSecurityGroup-create_and_delete_security_groups\" WHERE (\"instance\" =~  /$Instance$/) AND  $timeFilter GROUP BY time($interval)"
    }
   ]
  },
  {
   "title": "Glance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "SELECT last(\"success\") FROM \"GlanceImages-create_and_list_image\" WHERE (\"instance\" =~  /$Instance$/) AND $timeFilter GROUP BY time(30s) fill(null)"
    }
   ]
  },
  {
   "title": "Nova",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "SELECT last(\"success\") FROM \"NovaServers-list_servers\" WHERE (\"instance\" =~  /$Instance$/) AND $timeFilter GROUP BY time(30s) fill(null)"
    }
   ]
  },
  { "title": "Placement", "type": "stat", "gridPos": { "h": 3, "w": 4, "x": 8, "y": 11 }, "options": { "reduceOptions": { "calcs": [ "mean" ] } } },
  { "title": "Internal Network", "type": "stat", "gridPos": { "h": 3, "w": 6, "x": 12, "y": 11 }, "options": { "reduceOptions": { "calcs": [ "mean" ] } } },
  { "title": "Private Network", "type": "stat", "gridPos": { "h": 3, "w": 6, "x": 18, "y": 11 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  { "type": "mxswat-separator-panel", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  { "title": "Storage Overview", "type": "stat", "gridPos": { "h": 2, "w": 12, "x": 0, "y": 15 }, "options": { "reduceOptions": { "calcs": [ "mean" ] } } },
  { "title": "Web UI", "type": "stat", "gridPos": { "h": 2, "w": 12, "x": 12, "y": 15 }, "options": { "reduceOptions": { "calcs": [ "mean" ] } } },
  {
   "title": "Cinder",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "SELECT last(\"success\") FROM \"CinderVolumes-create_and_delete_volume\" WHERE (\"instance\" =~  /$Instance$/) AND $timeFilter GROUP BY time(30s) fill(null)"
    }
   ]
  },
  { "title": "Manila", "type": "stat", "gridPos": { "h": 3, "w": 6, "x": 6, "y": 17 }, "options": { "reduceOptions": { "calcs": [ "mean" ] } } },
  { "title": "openstack.stfc.ac.uk", "type": "stat", "gridPos": { "h": 3, "w": 6, "x": 12, "y": 17 }, "options": { "reduceOptions": { "calcs": [ "mean" ] } } },
  { "title": "cloud.stfc.ac.uk", "type": "stat", "gridPos": { "h": 3, "w": 6, "x": 18, "y": 17 }, "options": { "reduceOptions": { "calcs": [ "mean" ] } } },
  { "type": "mxswat-separator-panel", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  { "title": "Octavia", "type": "stat", "gridPos": { "h": 3, "w": 12, "x": 0, "y": 21 }, "options": { "reduceOptions": { "calcs": [ "mean" ] } } },
  {
   "title": "Heat",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "SELECT last(\"success\") FROM \"HeatStacks-create_and_list_stack\" WHERE (\"instance\" =~  /$Instance$/) AND $timeFilter GROUP BY time(30s) fill(null)"
    }
   ]
  }
 ]
}