{
 "title": "OpenStack Services Graphs",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Instance", "query": "Prod, PreProd" }
  ]
 },
 "panels": [
  {
   "title": "OpenStack Services",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# OpenStack Services: ${Instance}\n\nGraphs of service availability"
   }
  },
  {
   "title": "VM Creation (Internal)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "query": "SELECT mean(\"success\") FROM \"VMTasks-boot_runcommand_delete\" WHERE (\"instance\" =~  /^$Instance$/ AND \"network\" != 'MonitoringPrivate') AND $timeFilter GROUP BY time($interval) fill(null)"
    }
   ]
  },
  {
   "title": "VM Creation (Private)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "query": "SELECT mean(\"success\") FROM \"VMTasks-boot_runcommand_delete\" WHERE (\"instance\" =~  /$Instance$/ AND \"network\" = 'MonitoringPrivate') AND  $timeFilter GROUP BY time($interval)"
    }
   ]
  },
  {
   "title": "Keystone",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 13 },
   "targets": [
    {
     "query": "SELECT last(\"success\") FROM \"KeystoneBasic-create_tenant_with_users\" WHERE (\"instance\" =~  /^$Instance$/) AND  $timeFilter GROUP BY time($interval) fill(null)"
    }
   ]
  },
  {
   "title": "Neutron",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 13 },
   "targets": [
    {
     "query": "SELECT last(\"success\") FROM \"NeutronSecurityGroup-create_and_delete_security_groups\" WHERE (\"instance\" =~  /^$Instance$/) AND  $timeFilter GROUP BY time($interval)"
    }
   ]
  },
  {
   "title": "Glance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 13 },
   "targets": [
    {
     "query": "SELECT last(\"success\") FROM \"GlanceImages-create_and_list_image\" WHERE (\"instance\" =~  /^$Instance$/) AND $timeFilter GROUP BY time(30s) fill(null)"
    }
   ]
  },
  {
   "title": "Nova",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 13 },
   "targets": [
    {
     "query": "SELECT last(\"success\") FROM \"NovaServers-list_servers\" WHERE (\"instance\" =~  /^$Instance$/) AND $timeFilter GROUP BY time($interval) fill(null)"
    }
   ]
  },
  {
   "title": "Placement",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 22 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cinder",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 22 },
   "targets": [
    {
     "query": "SELECT last(\"success\") FROM \"CinderVolumes-create_and_delete_volume\" WHERE (\"instance\" =~  /^$Instance$/) AND $timeFilter GROUP BY time(30s) fill(null)"
    }
   ]
  },
  {
   "title": "Manila",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 22 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Heat",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 22 },
   "targets": [
    {
     "query": "SELECT last(\"success\") FROM \"HeatStacks-create_and_list_stack\" WHERE (\"instance\" =~  /^$Instance$/) AND $timeFilter GROUP BY time(30s) fill(null)"
    }
   ]
  }
 ]
}