{
 "title": "OpenStack Hypervisor Overview",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Instance", "query": "Prod, PreProd" }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT sum(\"agent\") FROM \"autogen\".\"ServiceStatus\" WHERE (\"instance\" =~ /^$Instance$/ AND \"service\" = '\"hv\"') AND $timeFilter GROUP BY time(15m) fill(null)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT sum(\"cpumax\") FROM \"autogen\".\"ServiceStatus\" WHERE (\"instance\" =~ /^$Instance$/ AND \"service\" = '\"hv\"') AND $timeFilter GROUP BY time(15m) fill(null)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "SELECT sum(\"memorymax\") FROM \"autogen\".\"ServiceStatus\" WHERE (\"instance\" =~ /^$Instance$/ AND \"service\" = '\"hv\"') AND $timeFilter GROUP BY time(15m) fill(null)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 2 },
   "options": {
    "content": "_________________________________________"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 2 },
   "options": {
    "content": "<h1><p style=\"text-align: center\">%UP</p></h1>\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 2 },
   "options": {
    "content": "<h1><p style=\"text-align: center\">%DOWN</p></h1>\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 2 },
   "options": {
    "content": "<h1><p style=\"text-align: center\">%ENABLED</p></h1>\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 2 },
   "options": {
    "content": "<h1><p style=\"text-align: center\">%DISABLED</p></h1>\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "options": {
    "content": "<h1><p style=\"text-align: center\">HV Status</p></h1>\n"
   }
  },
  {
   "title": "% Up",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($A / $B) * 100", "type": "math" }
   ]
  },
  {
   "title": "% Down",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($A / $B) * 100", "type": "math" }
   ]
  },
  {
   "title": "% Enabled",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($A / $B) * 100", "type": "math" }
   ]
  },
  {
   "title": "% Disabled",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($A / $B) * 100", "type": "math" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 7 },
   "options": {
    "content": "_______________________________________"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 7 },
   "options": {
    "content": "<h1><p style=\"text-align: center\">%ENABLED</p></h1>\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 7 },
   "options": {
    "content": "<h1><p style=\"text-align: center\">%USED</p></h1>\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 5, "x": 12, "y": 7 },
   "options": {
    "content": "<h1><p style=\"text-align: center\">%ENABLED USED</p></h1>\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "options": {
    "content": "<h1><p style=\"text-align: center\">CPU</p></h1>\n"
   }
  },
  {
   "title": "% CPU Enabled",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($A / $B) * 100", "type": "math" }
   ]
  },
  {
   "title": "% CPU Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($A / $B) * 100", "type": "math" }
   ]
  },
  {
   "title": "% Memory Enabled",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($A / $B) * 100", "type": "math" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 12 },
   "options": {
    "content": "<h1><p style=\"text-align: center\">Memory</p></h1>\n"
   }
  },
  {
   "title": "% Memory Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($A / $B) * 100", "type": "math" }
   ]
  },
  {
   "title": "% CPU Used of Enabled",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($A / $B) * 100", "type": "math" }
   ]
  },
  {
   "title": "% Memory Used of Enabled",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($A / $B) * 100", "type": "math" }
   ]
  }
 ]
}