{
 "title": "CPU benchmarks",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Image",
    "label": "Image",
    "query": "ubuntu-focal-20.04-nogui, rocky-8-nogui, ubuntu-focal-20.04-gui, rocky-9-nogui"
   },
   {
    "name": "Flavor",
    "label": "Flavor",
    "query": "l6.c2, l6.c4, l6.c8, l6.c16, l6.c32, l6.c64, l6.124, l3.nano, l3.micro, l3.tiny, l3.xsmall, l3.small, l5.c2, l5.c4, l5.c8, l5.c16, l5.c32, l5.c64, l5.c124"
   },
   {
    "name": "test_type",
    "label": "test type",
    "query": "primes_single, primes_multi, fft_single, fft_multi"
   }
  ]
 },
 "panels": [
  {
   "title": "Lightweight Rust CPU benchmarks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Average score by flavor",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(flavor) (cpu_rust_result{test_type=\"$test_type\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "prime single core",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cpu_rust_result{image=~\"$Image\", flavor=~\"$Flavor\", test_type=\"primes_single\"}",
     "legendFormat": "{{image}} | {{flavor}}"
    }
   ]
  },
  {
   "title": "fft single core",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cpu_rust_result{image=~\"$Image\", flavor=~\"$Flavor\", test_type=\"fft_single\"}",
     "legendFormat": "{{image}} | {{flavor}}"
    }
   ]
  },
  {
   "title": "prime multiore",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cpu_rust_result{image=~\"$Image\", flavor=~\"$Flavor\", test_type=\"primes_multi\"}",
     "legendFormat": "{{image}} | {{flavor}}"
    }
   ]
  },
  {
   "title": "fft multicore",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cpu_rust_result{image=~\"$Image\", flavor=~\"$Flavor\", test_type=\"fft_multi\"}",
     "legendFormat": "{{image}} | {{flavor}}"
    }
   ]
  },
  { "title": "HEPScore", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Average runtime by flavor",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(flavor) (hepscore_run_time)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average HEPScore by flavor",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(flavor) (hepscore_score)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HEPScore - Run time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "hepscore_run_time{flavor=~\"$Flavor\"}",
     "legendFormat": "{{flavor}}"
    }
   ]
  },
  {
   "title": "HEPScore - Score",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "hepscore_score{flavor=~\"$Flavor\"}",
     "legendFormat": "{{flavor}}"
    }
   ]
  }
 ]
}