{
 "title": "Ram benchmarking",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Image",
    "label": "Image",
    "query": "ubuntu-focal-20.04-nogui, rocky-8-nogui, ubuntu-focal-20.04-gui, rocky-9-nogui"
   },
   {
    "name": "Flavor",
    "label": "Flavor",
    "query": "l6.c2, l6.c4, l6.c8, l6.c16, l6.c32, l6.c64, l6.124, l3.nano, l3.micro, l3.tiny, l3.xsmall, l3.small, l5.c2, l5.c4, l5.c8, l5.c16, l5.c32, l5.c64, l5.c124"
   },
   { "name": "Block_size", "label": "Block_size", "query": "1K, 1M, 1G" }
  ]
 },
 "panels": [
  {
   "title": "Read speed",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "expr": "ram_read_speed{image=~\"$Image\", flavor=~\"$Flavor\", block_size=~\"$Block_size\"}",
     "legendFormat": "{{image}} | {{flavor}} | {{block_size}}"
    }
   ]
  },
  {
   "title": "Write speed",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "expr": "ram_write_speed{image=~\"$Image\", flavor=~\"$Flavor\", block_size=~\"$Block_size\"}",
     "legendFormat": "{{image}} | {{flavor}} | {{block_size}}"
    }
   ]
  },
  {
   "title": "Read latency",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "ram_read_latency{image=~\"$Image\", flavor=~\"$Flavor\", block_size=~\"$Block_size\"}",
     "legendFormat": "{{image}} | {{flavor}} | {{block_size}}"
    }
   ]
  },
  {
   "title": "Write latency",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "ram_write_latency{image=~\"$Image\", flavor=~\"$Flavor\", block_size=~\"$Block_size\"}",
     "legendFormat": "{{image}} | {{flavor}} | {{block_size}}"
    }
   ]
  }
 ]
}