{
 "title": "Meerkat-storage",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Image",
    "label": "Image",
    "query": "ubuntu-focal-20.04-nogui, ubuntu-focal-20.04-gui, rocky-8-nogui, rocky-9-nogui"
   },
   {
    "name": "Flavor",
    "label": "Flavor",
    "query": "l3.nano, l3.micro, l3.tiny, l3.xsmall, l3.small, l5.c4, l5.c8, l6.c4, l6.c8"
   },
   { "name": "File_size", "label": "File_size", "query": "kb, mb, gb" },
   {
    "name": "test_type",
    "label": "Test type",
    "query": "sequential_write, sequential_read, random_write, random_read"
   }
  ]
 },
 "panels": [
  { "title": "Detailed time series", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Local storage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "storage_local{image=~\"$Image\", flavor=~\"$Flavor\", file_size=~\"$File_size\", test_type=~\"$test_type\"}",
     "legendFormat": "{{image}} | {{flavor}} | {{test_type}} | {{file_size}}"
    }
   ]
  },
  {
   "title": "Volume storage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "storage_volume{image=~\"$Image\", flavor=~\"$Flavor\", file_size=~\"$File_size\", test_type=~\"$test_type\"}",
     "legendFormat": "{{image}} | {{flavor}} | {{test_type}} | {{file_size}}"
    }
   ]
  },
  {
   "title": "Manila",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "storage_manila{image=~\"$Image\", flavor=~\"$Flavor\", file_size=~\"$File_size\", test_type=~\"$test_type\"}",
     "legendFormat": "{{image}} | {{flavor}} | {{test_type}} | {{file_size}}"
    }
   ]
  },
  { "title": "Average speed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Average speed local storage",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(image) (storage_local{image!=\"hello\"})",
     "legendFormat": "{{image}} "
    }
   ]
  },
  {
   "title": "Average speed volume storage",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(image) (storage_volume{image!=\"hello\"})",
     "legendFormat": "{{image}} "
    }
   ]
  },
  {
   "title": "Average speed manila storage",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(image) (storage_manila{image!=\"hello\"})",
     "legendFormat": "{{image}} "
    }
   ]
  },
  {
   "title": "Average speed local storage",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(test_type, file_size) (storage_local{image!=\"hello\"})",
     "legendFormat": "{{file_size}} | {{test_type}} "
    }
   ]
  },
  {
   "title": "Average speed volume storage",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(test_type, file_size) (storage_volume{image!=\"hello\"})",
     "legendFormat": "{{file_size}} | {{test_type}} "
    }
   ]
  },
  {
   "title": "Average speed manila storage",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(test_type, file_size) (storage_manila{image!=\"hello\"})",
     "legendFormat": "{{file_size}} | {{test_type}} "
    }
   ]
  }
 ]
}