{
 "title": "Weekly Reporting",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "environment", "label": "Cloud Instance", "query": "prod, dev" }
  ]
 },
 "panels": [
  { "title": "Cloud CPU Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU in use",
   "type": "stat",
   "description": "CPUs in use by the Cloud hypervisors",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Cores" } },
   "targets": [
    {
     "query": "bucket = if string(v: \"${environment}\") == \"prod\" then \"weekly-reporting-bucket\" else \"weekly-reporting-dev\"\r\n\r\ndata = from(bucket: bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"in_use\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n\r\nreduced = data\r\n  |> reduce(\r\n      identity: {first: 0.0, last: 0.0, dummy: \"join_key\"},\r\n      fn: (r, accumulator) => ({\r\n          first: if accumulator.first == 0.0 then r._value else accumulator.first,\r\n          last: r._value,\r\n          dummy: \"join_key\"\r\n      })\r\n  )\r\n\r\nlatest = data\r\n  |> last()\r\n  |> map(fn: (r) => ({_value: r._value, dummy: \"join_key\"})) // Add dummy column for join\r\n\r\njoined = join(\r\n  tables: {reduced: reduced, latest: latest},\r\n  on: [\"dummy\"] // Join on the dummy column\r\n)\r\n\r\njoined\r\n  |> map(fn: (r) => ({\r\n      _time: now(),\r\n      Current: r._value,\r\n      \"Difference from time range\": r.last - r.first\r\n  }))\r\n"
    }
   ]
  },
  {
   "title": "CPU total",
   "type": "stat",
   "description": "CPUs totally available by the Cloud hypervisors",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Cores" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "bucket = if string(v: \"${environment}\") == \"prod\" then \"weekly-reporting-bucket\" else \"weekly-reporting-dev\"\r\n\r\ndata = from(bucket: bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"total\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n\r\nreduced = data\r\n  |> reduce(\r\n      identity: {first: 0.0, last: 0.0, dummy: \"join_key\"},\r\n      fn: (r, accumulator) => ({\r\n          first: if accumulator.first == 0.0 then r._value else accumulator.first,\r\n          last: r._value,\r\n          dummy: \"join_key\"\r\n      })\r\n  )\r\n\r\nlatest = data\r\n  |> last()\r\n  |> map(fn: (r) => ({_value: r._value, dummy: \"join_key\"})) // Add dummy column for join\r\n\r\njoined = join(\r\n  tables: {reduced: reduced, latest: latest},\r\n  on: [\"dummy\"] // Join on the dummy column\r\n)\r\n\r\njoined\r\n  |> map(fn: (r) => ({\r\n      _time: now(),\r\n      Current: r._value,\r\n      \"Difference from time range\": r.last - r.first\r\n  }))\r\n"
    }
   ]
  },
  {
   "title": "Cloud Virtual Worker Nodes",
   "type": "stat",
   "description": "Number of Cloud virtual worker nodes in the condor project running",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Nodes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "bucket = if string(v: \"${environment}\") == \"prod\" then \"weekly-reporting-bucket\" else \"weekly-reporting-dev\"\r\n\r\ndata = from(bucket: bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"virtual_worker_nodes\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"active\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n\r\nreduced = data\r\n  |> reduce(\r\n      identity: {first: 0.0, last: 0.0, dummy: \"join_key\"},\r\n      fn: (r, accumulator) => ({\r\n          first: if accumulator.first == 0.0 then r._value else accumulator.first,\r\n          last: r._value,\r\n          dummy: \"join_key\"\r\n      })\r\n  )\r\n\r\nlatest = data\r\n  |> last()\r\n  |> map(fn: (r) => ({_value: r._value, dummy: \"join_key\"})) // Add dummy column for join\r\n\r\njoined = join(\r\n  tables: {reduced: reduced, latest: latest},\r\n  on: [\"dummy\"] // Join on the dummy column\r\n)\r\n\r\njoined\r\n  |> map(fn: (r) => ({\r\n      _time: now(),\r\n      Current: r._value,\r\n      \"Difference from time range\": r.last - r.first\r\n  }))\r\n"
    }
   ]
  },
  {
   "title": "CPU in use past 30 days",
   "type": "timeseries",
   "description": "CPUs in use by the Cloud hypervisors",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Cores" } },
   "targets": [
    {
     "query": "bucket = if string(v: \"${environment}\") == \"prod\" then \"weekly-reporting-bucket\" else \"weekly-reporting-dev\"\r\n\r\ndata = from(bucket: bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"in_use\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "CPU total past 30 days",
   "type": "timeseries",
   "description": "CPU total of the Cloud hypervisors",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Cores" } },
   "targets": [
    {
     "query": "bucket = if string(v: \"${environment}\") == \"prod\" then \"weekly-reporting-bucket\" else \"weekly-reporting-dev\"\r\n\r\ndata = from(bucket: bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"total\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Active Virtual Worker Nodes past 30 days",
   "type": "timeseries",
   "description": "Active Cloud Virtual Worker Nodes",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Nodes" } },
   "targets": [
    {
     "query": "bucket = if string(v: \"${environment}\") == \"prod\" then \"weekly-reporting-bucket\" else \"weekly-reporting-dev\"\r\n\r\ndata = from(bucket: bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"virtual_worker_nodes\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"active\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "Cloud Memory Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Memory in use",
   "type": "stat",
   "description": "Memory in use by the Cloud hypervisors",
   "gridPos": { "h": 4, "w": 8, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dectbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "bucket = if string(v: \"${environment}\") == \"prod\" then \"weekly-reporting-bucket\" else \"weekly-reporting-dev\"\r\n\r\ndata = from(bucket: bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"memory\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"in_use\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n\r\nreduced = data\r\n  |> reduce(\r\n      identity: {first: 0.0, last: 0.0, dummy: \"join_key\"},\r\n      fn: (r, accumulator) => ({\r\n          first: if accumulator.first == 0.0 then r._value else accumulator.first,\r\n          last: r._value,\r\n          dummy: \"join_key\"\r\n      })\r\n  )\r\n\r\nlatest = data\r\n  |> last()\r\n  |> map(fn: (r) => ({_value: r._value, dummy: \"join_key\"})) // Add dummy column for join\r\n\r\njoined = join(\r\n  tables: {reduced: reduced, latest: latest},\r\n  on: [\"dummy\"] // Join on the dummy column\r\n)\r\n\r\njoined\r\n  |> map(fn: (r) => ({\r\n      _time: now(),\r\n      Current: r._value,\r\n      \"Difference from time range\": r.last - r.first\r\n  }))\r\n"
    }
   ]
  },
  {
   "title": "Memory Total",
   "type": "stat",
   "description": "Memory totally available by the Cloud hypervisors",
   "gridPos": { "h": 4, "w": 8, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dectbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "bucket = if string(v: \"${environment}\") == \"prod\" then \"weekly-reporting-bucket\" else \"weekly-reporting-dev\"\r\n\r\ndata = from(bucket: bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"memory\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"total\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n\r\nreduced = data\r\n  |> reduce(\r\n      identity: {first: 0.0, last: 0.0, dummy: \"join_key\"},\r\n      fn: (r, accumulator) => ({\r\n          first: if accumulator.first == 0.0 then r._value else accumulator.first,\r\n          last: r._value,\r\n          dummy: \"join_key\"\r\n      })\r\n  )\r\n\r\nlatest = data\r\n  |> last()\r\n  |> map(fn: (r) => ({_value: r._value, dummy: \"join_key\"})) // Add dummy column for join\r\n\r\njoined = join(\r\n  tables: {reduced: reduced, latest: latest},\r\n  on: [\"dummy\"] // Join on the dummy column\r\n)\r\n\r\njoined\r\n  |> map(fn: (r) => ({\r\n      _time: now(),\r\n      Current: r._value,\r\n      \"Difference from time range\": r.last - r.first\r\n  }))\r\n"
    }
   ]
  },
  {
   "title": "Memory in use past 30 days",
   "type": "timeseries",
   "description": "Memory in use by the Cloud hypervisors",
   "gridPos": { "h": 4, "w": 8, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "dectbytes" } },
   "targets": [
    {
     "query": "bucket = if string(v: \"${environment}\") == \"prod\" then \"weekly-reporting-bucket\" else \"weekly-reporting-dev\"\r\n\r\ndata = from(bucket: bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"memory\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"in_use\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Memory total past 30 days",
   "type": "timeseries",
   "description": "Memory total of the Cloud hypervisors",
   "gridPos": { "h": 4, "w": 8, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "dectbytes" } },
   "targets": [
    {
     "query": "bucket = if string(v: \"${environment}\") == \"prod\" then \"weekly-reporting-bucket\" else \"weekly-reporting-dev\"\r\n\r\ndata = from(bucket: bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"memory\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"total\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "Hypervisor Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "HVs Active",
   "type": "stat",
   "description": "Cloud hypervisors active",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "HVs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "bucket = if string(v: \"${environment}\") == \"prod\" then \"weekly-reporting-bucket\" else \"weekly-reporting-dev\"\r\n\r\ndata = from(bucket: bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"hv\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"up\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n\r\nreduced = data\r\n  |> reduce(\r\n      identity: {first: 0.0, last: 0.0, dummy: \"join_key\"},\r\n      fn: (r, accumulator) => ({\r\n          first: if accumulator.first == 0.0 then r._value else accumulator.first,\r\n          last: r._value,\r\n          dummy: \"join_key\"\r\n      })\r\n  )\r\n\r\nlatest = data\r\n  |> last()\r\n  |> map(fn: (r) => ({_value: r._value, dummy: \"join_key\"})) // Add dummy column for join\r\n\r\njoined = join(\r\n  tables: {reduced: reduced, latest: latest},\r\n  on: [\"dummy\"] // Join on the dummy column\r\n)\r\n\r\njoined\r\n  |> map(fn: (r) => ({\r\n      _time: now(),\r\n      Current: r._value,\r\n      \"Difference from time range\": r.last - r.first\r\n  }))\r\n"
    }
   ]
  },
  {
   "title": "HVs Active and CPU Full",
   "type": "stat",
   "description": "Cloud hypervisors active and CPU full",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "HVs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "bucket = if string(v: \"${environment}\") == \"prod\" then \"weekly-reporting-bucket\" else \"weekly-reporting-dev\"\r\n\r\ndata = from(bucket: bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"hv\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"active_and_cpu_full\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n\r\nreduced = data\r\n  |> reduce(\r\n      identity: {first: 0.0, last: 0.0, dummy: \"join_key\"},\r\n      fn: (r, accumulator) => ({\r\n          first: if accumulator.first == 0.0 then r._value else accumulator.first,\r\n          last: r._value,\r\n          dummy: \"join_key\"\r\n      })\r\n  )\r\n\r\nlatest = data\r\n  |> last()\r\n  |> map(fn: (r) => ({_value: r._value, dummy: \"join_key\"})) // Add dummy column for join\r\n\r\njoined = join(\r\n  tables: {reduced: reduced, latest: latest},\r\n  on: [\"dummy\"] // Join on the dummy column\r\n)\r\n\r\njoined\r\n  |> map(fn: (r) => ({\r\n      _time: now(),\r\n      Current: r._value,\r\n      \"Difference from time range\": r.last - r.first\r\n  }))\r\n"
    }
   ]
  },
  {
   "title": "HVs Active and Memory Full",
   "type": "stat",
   "description": "Cloud hypervisors active and memory full",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "HVs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "bucket = if string(v: \"${environment}\") == \"prod\" then \"weekly-reporting-bucket\" else \"weekly-reporting-dev\"\r\n\r\ndata = from(bucket: bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"hv\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"active_and_memory_full\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n\r\nreduced = data\r\n  |> reduce(\r\n      identity: {first: 0.0, last: 0.0, dummy: \"join_key\"},\r\n      fn: (r, accumulator) => ({\r\n          first: if accumulator.first == 0.0 then r._value else accumulator.first,\r\n          last: r._value,\r\n          dummy: \"join_key\"\r\n      })\r\n  )\r\n\r\nlatest = data\r\n  |> last()\r\n  |> map(fn: (r) => ({_value: r._value, dummy: \"join_key\"})) // Add dummy column for join\r\n\r\njoined = join(\r\n  tables: {reduced: reduced, latest: latest},\r\n  on: [\"dummy\"] // Join on the dummy column\r\n)\r\n\r\njoined\r\n  |> map(fn: (r) => ({\r\n      _time: now(),\r\n      Current: r._value,\r\n      \"Difference from time range\": r.last - r.first\r\n  }))\r\n"
    }
   ]
  },
  {
   "title": "Hypervisors up past 30 days",
   "type": "timeseries",
   "description": "Cloud Hypervisors up",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "HVs" } },
   "targets": [
    {
     "query": "bucket = if string(v: \"${environment}\") == \"prod\" then \"weekly-reporting-bucket\" else \"weekly-reporting-dev\"\r\n\r\ndata = from(bucket: bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"hv\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"up\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "HVs Down",
   "type": "stat",
   "description": "Cloud hypervisors down",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "HVs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "bucket = if string(v: \"${environment}\") == \"prod\" then \"weekly-reporting-bucket\" else \"weekly-reporting-dev\"\r\n\r\ndata = from(bucket: bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"hv\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"down\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n\r\nreduced = data\r\n  |> reduce(\r\n      identity: {first: 0.0, last: 0.0, dummy: \"join_key\"},\r\n      fn: (r, accumulator) => ({\r\n          first: if accumulator.first == 0.0 then r._value else accumulator.first,\r\n          last: r._value,\r\n          dummy: \"join_key\"\r\n      })\r\n  )\r\n\r\nlatest = data\r\n  |> last()\r\n  |> map(fn: (r) => ({_value: r._value, dummy: \"join_key\"})) // Add dummy column for join\r\n\r\njoined = join(\r\n  tables: {reduced: reduced, latest: latest},\r\n  on: [\"dummy\"] // Join on the dummy column\r\n)\r\n\r\njoined\r\n  |> map(fn: (r) => ({\r\n      _time: now(),\r\n      Current: r._value,\r\n      \"Difference from time range\": r.last - r.first\r\n  }))\r\n"
    }
   ]
  },
  {
   "title": "HVs Disabled",
   "type": "stat",
   "description": "Cloud hypervisors disabled",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "HVs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "bucket = if string(v: \"${environment}\") == \"prod\" then \"weekly-reporting-bucket\" else \"weekly-reporting-dev\"\r\n\r\ndata = from(bucket: bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"hv\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disabled\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n\r\nreduced = data\r\n  |> reduce(\r\n      identity: {first: 0.0, last: 0.0, dummy: \"join_key\"},\r\n      fn: (r, accumulator) => ({\r\n          first: if accumulator.first == 0.0 then r._value else accumulator.first,\r\n          last: r._value,\r\n          dummy: \"join_key\"\r\n      })\r\n  )\r\n\r\nlatest = data\r\n  |> last()\r\n  |> map(fn: (r) => ({_value: r._value, dummy: \"join_key\"})) // Add dummy column for join\r\n\r\njoined = join(\r\n  tables: {reduced: reduced, latest: latest},\r\n  on: [\"dummy\"] // Join on the dummy column\r\n)\r\n\r\njoined\r\n  |> map(fn: (r) => ({\r\n      _time: now(),\r\n      Current: r._value,\r\n      \"Difference from time range\": r.last - r.first\r\n  }))\r\n"
    }
   ]
  },
  { "title": "VM Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "VMs Active",
   "type": "stat",
   "description": "Cloud virtual machines active",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "VMs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "bucket = if string(v: \"${environment}\") == \"prod\" then \"weekly-reporting-bucket\" else \"weekly-reporting-dev\"\r\n\r\ndata = from(bucket: bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vm\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"active\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n\r\nreduced = data\r\n  |> reduce(\r\n      identity: {first: 0.0, last: 0.0, dummy: \"join_key\"},\r\n      fn: (r, accumulator) => ({\r\n          first: if accumulator.first == 0.0 then r._value else accumulator.first,\r\n          last: r._value,\r\n          dummy: \"join_key\"\r\n      })\r\n  )\r\n\r\nlatest = data\r\n  |> last()\r\n  |> map(fn: (r) => ({_value: r._value, dummy: \"join_key\"})) // Add dummy column for join\r\n\r\njoined = join(\r\n  tables: {reduced: reduced, latest: latest},\r\n  on: [\"dummy\"] // Join on the dummy column\r\n)\r\n\r\njoined\r\n  |> map(fn: (r) => ({\r\n      _time: now(),\r\n      Current: r._value,\r\n      \"Difference from time range\": r.last - r.first\r\n  }))\r\n"
    }
   ]
  },
  {
   "title": "VMs active past 30 days",
   "type": "timeseries",
   "description": "Virtual Machines active",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "VMs" } },
   "targets": [
    {
     "query": "bucket = if string(v: \"${environment}\") == \"prod\" then \"weekly-reporting-bucket\" else \"weekly-reporting-dev\"\r\n\r\ndata = from(bucket: bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vm\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"active\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "VMs Errored",
   "type": "stat",
   "description": "Cloud virtual machines error",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "VMs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "bucket = if string(v: \"${environment}\") == \"prod\" then \"weekly-reporting-bucket\" else \"weekly-reporting-dev\"\r\n\r\ndata = from(bucket: bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vm\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"error\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n\r\nreduced = data\r\n  |> reduce(\r\n      identity: {first: 0.0, last: 0.0, dummy: \"join_key\"},\r\n      fn: (r, accumulator) => ({\r\n          first: if accumulator.first == 0.0 then r._value else accumulator.first,\r\n          last: r._value,\r\n          dummy: \"join_key\"\r\n      })\r\n  )\r\n\r\nlatest = data\r\n  |> last()\r\n  |> map(fn: (r) => ({_value: r._value, dummy: \"join_key\"})) // Add dummy column for join\r\n\r\njoined = join(\r\n  tables: {reduced: reduced, latest: latest},\r\n  on: [\"dummy\"] // Join on the dummy column\r\n)\r\n\r\njoined\r\n  |> map(fn: (r) => ({\r\n      _time: now(),\r\n      Current: r._value,\r\n      \"Difference from time range\": r.last - r.first\r\n  }))\r\n"
    }
   ]
  },
  {
   "title": "VMs Shutoff",
   "type": "stat",
   "description": "Cloud virtual machines shutoff",
   "gridPos": { "h": 4, "w": 8, "x": 4, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "VMs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "bucket = if string(v: \"${environment}\") == \"prod\" then \"weekly-reporting-bucket\" else \"weekly-reporting-dev\"\r\n\r\ndata = from(bucket: bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vm\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"shutoff\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n\r\nreduced = data\r\n  |> reduce(\r\n      identity: {first: 0.0, last: 0.0, dummy: \"join_key\"},\r\n      fn: (r, accumulator) => ({\r\n          first: if accumulator.first == 0.0 then r._value else accumulator.first,\r\n          last: r._value,\r\n          dummy: \"join_key\"\r\n      })\r\n  )\r\n\r\nlatest = data\r\n  |> last()\r\n  |> map(fn: (r) => ({_value: r._value, dummy: \"join_key\"})) // Add dummy column for join\r\n\r\njoined = join(\r\n  tables: {reduced: reduced, latest: latest},\r\n  on: [\"dummy\"] // Join on the dummy column\r\n)\r\n\r\njoined\r\n  |> map(fn: (r) => ({\r\n      _time: now(),\r\n      Current: r._value,\r\n      \"Difference from time range\": r.last - r.first\r\n  }))\r\n"
    }
   ]
  },
  {
   "title": "VMs Building",
   "type": "stat",
   "description": "Cloud virtual machines build",
   "gridPos": { "h": 4, "w": 8, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "VMs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "bucket = if string(v: \"${environment}\") == \"prod\" then \"weekly-reporting-bucket\" else \"weekly-reporting-dev\"\r\n\r\ndata = from(bucket: bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vm\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"build\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n\r\nreduced = data\r\n  |> reduce(\r\n      identity: {first: 0.0, last: 0.0, dummy: \"join_key\"},\r\n      fn: (r, accumulator) => ({\r\n          first: if accumulator.first == 0.0 then r._value else accumulator.first,\r\n          last: r._value,\r\n          dummy: \"join_key\"\r\n      })\r\n  )\r\n\r\nlatest = data\r\n  |> last()\r\n  |> map(fn: (r) => ({_value: r._value, dummy: \"join_key\"})) // Add dummy column for join\r\n\r\njoined = join(\r\n  tables: {reduced: reduced, latest: latest},\r\n  on: [\"dummy\"] // Join on the dummy column\r\n)\r\n\r\njoined\r\n  |> map(fn: (r) => ({\r\n      _time: now(),\r\n      Current: r._value,\r\n      \"Difference from time range\": r.last - r.first\r\n  }))\r\n"
    }
   ]
  },
  { "title": "Floating IP Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Floating IPs consumed",
   "type": "stat",
   "description": "Floating IP addresses consumed in the Cloud",
   "gridPos": { "h": 4, "w": 8, "x": 3, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "FIPs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "bucket = if string(v: \"${environment}\") == \"prod\" then \"weekly-reporting-bucket\" else \"weekly-reporting-dev\"\r\n\r\ndata = from(bucket: bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"floating_ip\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"in_use\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n\r\nreduced = data\r\n  |> reduce(\r\n      identity: {first: 0.0, last: 0.0, dummy: \"join_key\"},\r\n      fn: (r, accumulator) => ({\r\n          first: if accumulator.first == 0.0 then r._value else accumulator.first,\r\n          last: r._value,\r\n          dummy: \"join_key\"\r\n      })\r\n  )\r\n\r\nlatest = data\r\n  |> last()\r\n  |> map(fn: (r) => ({_value: r._value, dummy: \"join_key\"})) // Add dummy column for join\r\n\r\njoined = join(\r\n  tables: {reduced: reduced, latest: latest},\r\n  on: [\"dummy\"] // Join on the dummy column\r\n)\r\n\r\njoined\r\n  |> map(fn: (r) => ({\r\n      _time: now(),\r\n      Current: r._value,\r\n      \"Difference from time range\": r.last - r.first\r\n  }))\r\n"
    }
   ]
  },
  {
   "title": "Floating IPs total",
   "type": "stat",
   "description": "Floating IP addresses total in the Cloud",
   "gridPos": { "h": 4, "w": 8, "x": 11, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "FIPs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "bucket = if string(v: \"${environment}\") == \"prod\" then \"weekly-reporting-bucket\" else \"weekly-reporting-dev\"\r\n\r\ndata = from(bucket: bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"floating_ip\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"total\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n\r\nreduced = data\r\n  |> reduce(\r\n      identity: {first: 0.0, last: 0.0, dummy: \"join_key\"},\r\n      fn: (r, accumulator) => ({\r\n          first: if accumulator.first == 0.0 then r._value else accumulator.first,\r\n          last: r._value,\r\n          dummy: \"join_key\"\r\n      })\r\n  )\r\n\r\nlatest = data\r\n  |> last()\r\n  |> map(fn: (r) => ({_value: r._value, dummy: \"join_key\"})) // Add dummy column for join\r\n\r\njoined = join(\r\n  tables: {reduced: reduced, latest: latest},\r\n  on: [\"dummy\"] // Join on the dummy column\r\n)\r\n\r\njoined\r\n  |> map(fn: (r) => ({\r\n      _time: now(),\r\n      Current: r._value,\r\n      \"Difference from time range\": r.last - r.first\r\n  }))\r\n"
    }
   ]
  },
  {
   "title": "FIPs in use past 30 days",
   "type": "timeseries",
   "description": "Floating IPs in use",
   "gridPos": { "h": 4, "w": 8, "x": 7, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "FIPs" } },
   "targets": [
    {
     "query": "bucket = if string(v: \"${environment}\") == \"prod\" then \"weekly-reporting-bucket\" else \"weekly-reporting-dev\"\r\n\r\ndata = from(bucket: bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"floating_ip\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"in_use\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Sirius Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sirius in use",
     "type": "stat",
     "description": "Sirius storage in use",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "dectbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"weekly-reporting-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sirius\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"in_use\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      },
      {
       "query": "from(bucket: \"weekly-reporting-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sirius\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"in_use\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "Sirius total",
     "type": "stat",
     "description": "Sirius storage total",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "dectbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"weekly-reporting-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sirius\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"total\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      },
      {
       "query": "from(bucket: \"weekly-reporting-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sirius\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"total\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "Sirius Nodes Active",
     "type": "stat",
     "description": "Sirius active nodes total",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "Nodes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"weekly-reporting-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sirius\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"nodes\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      },
      {
       "query": "from(bucket: \"weekly-reporting-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sirius\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"nodes\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    }
   ]
  },
  {
   "title": "Arided Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Arided in use",
     "type": "stat",
     "description": "Arided storage in use",
     "gridPos": { "h": 4, "w": 8, "x": 4, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "dectbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"weekly-reporting-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"arided\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"in_use\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      },
      {
       "query": "from(bucket: \"weekly-reporting-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"arided\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"in_use\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "Arided total",
     "type": "stat",
     "description": "Sirius storage total",
     "gridPos": { "h": 4, "w": 8, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "dectbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"weekly-reporting-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"arided\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"total\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      },
      {
       "query": "from(bucket: \"weekly-reporting-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"arided\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"total\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    }
   ]
  },
  {
   "title": "Deneb Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "Deneb in use",
     "type": "stat",
     "description": "Deneb storage in use",
     "gridPos": { "h": 4, "w": 8, "x": 4, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "dectbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"weekly-reporting-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"deneb\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"in_use\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      },
      {
       "query": "from(bucket: \"weekly-reporting-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"deneb\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"in_use\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "Deneb total",
     "type": "stat",
     "description": "Deneb storage total",
     "gridPos": { "h": 4, "w": 8, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "dectbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"weekly-reporting-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"deneb\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"total\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      },
      {
       "query": "from(bucket: \"weekly-reporting-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"deneb\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"total\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    }
   ]
  }
 ]
}