{
 "title": "monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "host_id", "label": "host", "query": "R89, R26, pnet, FIP, LB" }
  ]
 },
 "panels": [
  { "title": "Ping", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Round trip time average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "network_monitoring_rtt_average{host_id=~\"$host_id\"}",
     "legendFormat": "{{target_id}}"
    }
   ]
  },
  {
   "title": "Packet Loss",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "network_monitoring_rtt_packet_loss{host_id=~\"$host_id\"}",
     "legendFormat": "{{target_id}}"
    }
   ]
  },
  {
   "title": "Round trip time max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "network_monitoring_rtt_max{host_id=~\"$host_id\"}",
     "legendFormat": "{{target_id}}"
    }
   ]
  },
  { "title": "TCP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "TCP Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "network_monitoring_tcp_throughput{host_id=~\"$host_id\"}",
     "legendFormat": "{{target_id}}"
    }
   ]
  },
  {
   "title": "TCP Retires",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "network_monitoring_tcp_retries{host_id=~\"$host_id\"}",
     "legendFormat": "{{target_id}}"
    }
   ]
  },
  { "title": "UDP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "UDP Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "Gbits" } },
   "targets": [
    {
     "expr": "network_monitoring_udp_throughput{host_id=~\"$host_id\"}",
     "legendFormat": "{{target_id}}"
    }
   ]
  },
  {
   "title": "UDP packet loss",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "network_monitoring_udp_packet_loss{host_id=~\"$host_id\"}",
     "legendFormat": "{{target_id}}"
    }
   ]
  }
 ]
}