{
 "title": "Cloud Power Metrics",
 "time": { "from": "2023-12-01T00:00:00.000Z", "to": "2023-12-01T00:01:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "hosts",
    "label": "Hostname",
    "query": "{\"find\": \"terms\", \"field\": \"hostname.keyword\", \"size\": 3000}"
   }
  ]
 },
 "panels": [
  {
   "title": "Cloud Power Metrics",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": { "content": "# Cloud Power Metrics" },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Traces",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Current cloud power usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "watts", "id": "1", "type": "sum" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Number of machines monitored",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Max power from a single machine",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "watts", "id": "1", "type": "max" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "$hosts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 9 },
   "repeat": "hosts",
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "15m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "watts", "id": "1", "type": "avg" }
     ],
     "query": "hostname: \"$hosts\"",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}