{
 "title": "Cloud Energy Overview by Aggregate",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "aggregate", "label": "Aggregate", "query": { "query": "label_values(aggregates)" } },
   { "name": "carbon_intensity", "label": "Carbon Intensity", "query": "126" }
  ]
 },
 "panels": [
  {
   "title": "Power of All Aggregates",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ipmi_dcmi_power_consumption_watts)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All Aggregates Carbon Emission gCO2 per kWh",
   "type": "stat",
   "description": "UK average carbon intensity in 2025 is 126 gCO2/kWh. <br>\nSource: <br>\nhttps://www.carbonbrief.org/analysis-uk-renewables-enjoy-record-year-in-2025-but-gas-power-still-rises/ <br>\nhttps://www.energydashboard.co.uk/insights/2025-review",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ipmi_dcmi_power_consumption_watts)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Power of All Aggregates Time Series",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum(ipmi_dcmi_power_consumption_watts)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Aggregate Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Power of $aggregate",
     "type": "stat",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
     "repeat": "aggregate",
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(\r\n  label_replace(\r\n    last_over_time(ipmi_dcmi_power_consumption_watts[10m]),\r\n    \"hostname\", \"$1\", \"instance\", \"(.*)\"\r\n  )\r\n  and on(hostname)\r\n  last_over_time(openstack_nova_current_workload{aggregates=~\"$aggregate\"}[10m])\r\n)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Aggregate: $aggregate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 }, "repeat": "aggregate" },
  {
   "title": "Total Power per Aggregate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\r\n  label_replace(\r\n    last_over_time(ipmi_dcmi_power_consumption_watts[10m]),\r\n    \"hostname\", \"$1\", \"instance\", \"(.*)\"\r\n  )\r\n  and on(hostname)\r\n  last_over_time(openstack_nova_current_workload{aggregates=~\"$aggregate\"}[10m])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Watts per Used CPU Core (Aggregate)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\r\n  label_replace(\r\n    last_over_time(ipmi_dcmi_power_consumption_watts[10m]),\r\n    \"hostname\", \"$1\", \"instance\", \"(.*)\"\r\n  )\r\n  and on(hostname)\r\n  last_over_time(openstack_nova_current_workload{aggregates=~\"$aggregate\"}[10m])\r\n)\r\n/\r\nsum(\r\n  last_over_time(openstack_placement_resource_usage{resourcetype=~\"VCPU|PCPU\"}[10m])\r\n  and on(hostname)\r\n  last_over_time(openstack_nova_current_workload{aggregates=~\"$aggregate\"}[10m])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Watts per VM",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(label_replace(last_over_time(ipmi_dcmi_power_consumption_watts[10m]), \"hostname\", \"$1\", \"instance\", \"(.*)\")) and on(hostname) (last_over_time(openstack_nova_current_workload{aggregates=~\"$aggregate\"}[10m])) / (sum(last_over_time(openstack_nova_running_vms[10m])) and on(hostname) (last_over_time(openstack_nova_current_workload{aggregates=~\"$aggregate\"}[10m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Utilisation vs Power Efficiency",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\r\nlast_over_time(openstack_placement_resource_usage{resourcetype=~\"VCPU|PCPU\"}[10m])\r\nand on(hostname)\r\nlast_over_time(openstack_nova_current_workload{aggregates=~\"$aggregate\"}[10m])\r\n)\r\n/\r\nsum(\r\nlast_over_time(openstack_placement_resource_total{resourcetype=~\"VCPU|PCPU\"}[10m])\r\nand on(hostname)\r\nlast_over_time(openstack_nova_current_workload{aggregates=~\"$aggregate\"}[10m])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Per-Host Power",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\r\n  last_over_time(ipmi_dcmi_power_consumption_watts[10m]),\r\n  \"hostname\", \"$1\", \"instance\", \"(.*)\"\r\n)\r\nand on(hostname)\r\nlast_over_time(openstack_nova_current_workload{aggregates=~\"$aggregate\"}[10m])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Average Power Per Hypervisor in Aggregate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "avg(\r\n  label_replace(\r\n    last_over_time(ipmi_dcmi_power_consumption_watts[10m]),\r\n    \"hostname\", \"$1\", \"instance\", \"(.*)\"\r\n  )\r\n  and on(hostname)\r\n  last_over_time(openstack_nova_current_workload{aggregates=~\"$aggregate\"}[10m])\r\n)",
     "legendFormat": "Average Power{{label_name}}"
    }
   ]
  },
  {
   "title": "Total Power Per Aggregate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum(\r\n  label_replace(\r\n    last_over_time(ipmi_dcmi_power_consumption_watts[10m]),\r\n    \"hostname\", \"$1\", \"instance\", \"(.*)\"\r\n  )\r\n  and on(hostname)\r\n  last_over_time(openstack_nova_current_workload{aggregates=~\"$aggregate\"}[10m])\r\n)",
     "legendFormat": "Total Power{{label_name}}"
    }
   ]
  },
  {
   "title": "Number of VMS Per Hypervisor",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "last_over_time(openstack_nova_running_vms[30m]) and on(hostname) last_over_time(openstack_nova_current_workload{aggregates=~\"$aggregate\"}[30m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cores Used",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 6, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time(openstack_placement_resource_usage{resourcetype=~\"VCPU|PCPU\"}[10m]) and on(hostname) last_over_time(openstack_nova_current_workload{aggregates=~\"$aggregate\"}[15m])) / sum(last_over_time(openstack_placement_resource_total{resourcetype=~\"VCPU|PCPU\"}[10m]) and on(hostname) last_over_time(openstack_nova_current_workload{aggregates=~\"$aggregate\"}[15m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hypervisor Memory Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 10, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time(openstack_placement_resource_usage{resourcetype=\"MEMORY_MB\"}[30m]) and on(hostname) last_over_time(openstack_nova_current_workload{aggregates=~\"$aggregate\"}[30m])) / sum(last_over_time(openstack_placement_resource_total{resourcetype=\"MEMORY_MB\"}[30m]) and on(hostname) last_over_time(openstack_nova_current_workload{aggregates=~\"$aggregate\"}[30m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Local Storage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 14, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time(openstack_placement_resource_usage{resourcetype=\"DISK_GB\"}[30m]) and on(hostname) last_over_time(openstack_nova_current_workload{aggregates=~\"$aggregate\"}[30m])) / sum(last_over_time(openstack_placement_resource_total{resourcetype=\"DISK_GB\"}[30m]) and on(hostname) last_over_time(openstack_nova_current_workload{aggregates=~\"$aggregate\"}[30m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hypervisor State",
   "type": "piechart",
   "description": "Hypervisor count by state. Disabled stat counts disabled and up not down",
   "gridPos": { "h": 8, "w": 4, "x": 18, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(adminState) ((last_over_time(openstack_nova_agent_state{service=\"nova-compute\"}[30m]) and on(hostname) last_over_time(openstack_nova_current_workload{aggregates=~\"$aggregate\"}[30m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Other Power Monitoring Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 110 } },
  {
   "title": "HWMON Hypervisor Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 111 },
   "targets": [
    {
     "expr": "node_hwmon_power_average_watt{job=\"node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAPL Hypervisor Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 111 },
   "targets": [
    {
     "expr": "sum by(instance) (rate(node_rapl_package_joules_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}